"""initial tables

Revision ID: 0e848fcd9111
Revises: 
Create Date: 2026-04-30 12:45:05.655720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e848fcd9111'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workly_branch_id', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_branches_id'), 'branches', ['id'], unique=False)
    op.create_index(op.f('ix_branches_workly_branch_id'), 'branches', ['workly_branch_id'], unique=True)
    op.create_table('checklist_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_ru', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checklist_sections_id'), 'checklist_sections', ['id'], unique=False)
    op.create_table('checklist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('title_ru', sa.String(length=500), nullable=False),
    sa.Column('requires_photo', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['checklist_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checklist_items_id'), 'checklist_items', ['id'], unique=False)
    op.create_index(op.f('ix_checklist_items_section_id'), 'checklist_items', ['section_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workly_employee_id', sa.String(length=100), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_branch_id'), 'users', ['branch_id'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_users_workly_employee_id'), 'users', ['workly_employee_id'], unique=False)
    op.create_table('workly_employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workly_employee_id', sa.String(length=100), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('position', sa.String(length=255), nullable=True),
    sa.Column('is_director', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workly_employees_branch_id'), 'workly_employees', ['branch_id'], unique=False)
    op.create_index(op.f('ix_workly_employees_id'), 'workly_employees', ['id'], unique=False)
    op.create_index(op.f('ix_workly_employees_phone'), 'workly_employees', ['phone'], unique=False)
    op.create_index(op.f('ix_workly_employees_workly_employee_id'), 'workly_employees', ['workly_employee_id'], unique=True)
    op.create_table('shift_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('shift_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shift_checks_branch_id'), 'shift_checks', ['branch_id'], unique=False)
    op.create_index(op.f('ix_shift_checks_id'), 'shift_checks', ['id'], unique=False)
    op.create_index(op.f('ix_shift_checks_status'), 'shift_checks', ['status'], unique=False)
    op.create_index(op.f('ix_shift_checks_user_id'), 'shift_checks', ['user_id'], unique=False)
    op.create_table('check_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shift_check_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['checklist_items.id'], ),
    sa.ForeignKeyConstraint(['shift_check_id'], ['shift_checks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_check_answers_id'), 'check_answers', ['id'], unique=False)
    op.create_index(op.f('ix_check_answers_item_id'), 'check_answers', ['item_id'], unique=False)
    op.create_index(op.f('ix_check_answers_shift_check_id'), 'check_answers', ['shift_check_id'], unique=False)
    op.create_table('answer_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.String(length=1000), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=1000), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['check_answers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answer_photos_answer_id'), 'answer_photos', ['answer_id'], unique=False)
    op.create_index(op.f('ix_answer_photos_id'), 'answer_photos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_answer_photos_id'), table_name='answer_photos')
    op.drop_index(op.f('ix_answer_photos_answer_id'), table_name='answer_photos')
    op.drop_table('answer_photos')
    op.drop_index(op.f('ix_check_answers_shift_check_id'), table_name='check_answers')
    op.drop_index(op.f('ix_check_answers_item_id'), table_name='check_answers')
    op.drop_index(op.f('ix_check_answers_id'), table_name='check_answers')
    op.drop_table('check_answers')
    op.drop_index(op.f('ix_shift_checks_user_id'), table_name='shift_checks')
    op.drop_index(op.f('ix_shift_checks_status'), table_name='shift_checks')
    op.drop_index(op.f('ix_shift_checks_id'), table_name='shift_checks')
    op.drop_index(op.f('ix_shift_checks_branch_id'), table_name='shift_checks')
    op.drop_table('shift_checks')
    op.drop_index(op.f('ix_workly_employees_workly_employee_id'), table_name='workly_employees')
    op.drop_index(op.f('ix_workly_employees_phone'), table_name='workly_employees')
    op.drop_index(op.f('ix_workly_employees_id'), table_name='workly_employees')
    op.drop_index(op.f('ix_workly_employees_branch_id'), table_name='workly_employees')
    op.drop_table('workly_employees')
    op.drop_index(op.f('ix_users_workly_employee_id'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_branch_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_checklist_items_section_id'), table_name='checklist_items')
    op.drop_index(op.f('ix_checklist_items_id'), table_name='checklist_items')
    op.drop_table('checklist_items')
    op.drop_index(op.f('ix_checklist_sections_id'), table_name='checklist_sections')
    op.drop_table('checklist_sections')
    op.drop_index(op.f('ix_branches_workly_branch_id'), table_name='branches')
    op.drop_index(op.f('ix_branches_id'), table_name='branches')
    op.drop_table('branches')
    # ### end Alembic commands ###
