"""add_face_id_allowed_column

Revision ID: 17827dc086ad
Revises: 2aedf2a75c45
Create Date: 2026-05-20 11:54:41.222775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17827dc086ad'
down_revision: Union[str, Sequence[str], None] = '2aedf2a75c45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('face_id_allowed', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'face_id_allowed')
    # ### end Alembic commands ###
