"""add_user_passkeys_table

Revision ID: 2aedf2a75c45
Revises: b2c3d4e5f6a7
Create Date: 2026-05-18 12:55:54.265339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2aedf2a75c45'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_passkeys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('credential_id', sa.String(length=500), nullable=False),
    sa.Column('public_key', sa.LargeBinary(), nullable=False),
    sa.Column('device_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_passkeys_credential_id'), 'user_passkeys', ['credential_id'], unique=True)
    op.create_index(op.f('ix_user_passkeys_user_id'), 'user_passkeys', ['user_id'], unique=False)
    #op.drop_constraint(op.f('unique_workly_employee_id'), 'users', type_='unique')
    op.drop_constraint(op.f('uq_users_workly_employee_id'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_workly_employee_id'), table_name='users')
    op.create_index(op.f('ix_users_workly_employee_id'), 'users', ['workly_employee_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_workly_employee_id'), table_name='users')
    op.create_index(op.f('ix_users_workly_employee_id'), 'users', ['workly_employee_id'], unique=False)
    op.create_unique_constraint(op.f('uq_users_workly_employee_id'), 'users', ['workly_employee_id'], postgresql_nulls_not_distinct=False)
    #op.create_unique_constraint(op.f('unique_workly_employee_id'), 'users', ['workly_employee_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_user_passkeys_user_id'), table_name='user_passkeys')
    op.drop_index(op.f('ix_user_passkeys_credential_id'), table_name='user_passkeys')
    op.drop_table('user_passkeys')
    # ### end Alembic commands ###
